### PR TITLE
Adding rendering helper and server rendering support

### PR DESCRIPTION
**Pull request by wschenk**
Most of this code was ripped straight from react-rails.

### CODE REVIEW

**Comment by plasticine** [comment]
@wschenk I’m not really sure I like the idea of just ripping out bits of rails to get this working. For one I’m not sure that the rails solution really makes sense in the case of a static generator, but I also don’t like the idea of just aping their code across here...

**Comment by wschenk** [comment]
Looks like I need to update the pull request.  What don't you like about this solution?  The main thing that is copied over is the js code to make sure that react can reattach to the rendered components, but all of the middleman integration is obviously unrelated to the rails-react code.

**Comment by plasticine** [comment]
I realise that, however I'm not interested in copying that into this project, for several reasons. Sorry.

**Comment by wschenk** [comment]
Cool, if you could shed any more light on your reasoning that would be helpful, otherwise we can keep things separate no problem.

**Comment by plasticine** [comment]
> Cool, if you could shed any more light on your reasoning that would be helpful, otherwise we can keep things separate no problem.

@wschenk Sure thing.

Firstly, I should say really like the idea of being able to support “server side” rendering using `middleman-react`. It’s an awesome feature that I would love to support, but have never got around to :P

The main issue I have with cloning this code across from `react-rails` is that I don’t think this implementation actually makes sense in the context of a static site generator.

`react-rails` and all of its associated magic (`ujs` weirdness & connection pooling for shelling out to node from ruby) has to accommodate the dynamic nature of responses in rails—a problem that static sites will never have. React already supports server-side-rendering via `React.renderToString`. I would prefer a solution that simply embraces that pattern, and places the onus on the site author to take it from there.

Also, I don’t really like the idea of just copying code from another project.

Happy to hear your thoughts.

**Comment by wschenk** [comment]
Ah, I see, the dynamic data into a static generator is exactly the use case I'm trying to support.  I want to pull in the data from a database, use middleman to handle all of the sitemap stuff, and then prerender the pages based upon that dynamic data to get seo support.  In the simple case, inside of config.rb do something like

```
ready do
  data.products.do |product|
    page "/authors/#{product.id}.html", proxy: "product.html", locals: {product: product}
  end
end
```

and then `product.html.haml` has a mixture of prerendered  `= react_component 'author', { data: product }, {prerender: true}` and regular react tags, so that the site itself can be crawled by naive crawlers/seo, the hosting is totally static, and you can have build the app in one templating language.  I outlined my approach here: http://willschenk.com/slow-data-and-fast-sites/

The key feature to me is to support have a way to insert dynamic pages into the sitemap using existing templates that pull in dynamic data.

**Pull request closed without merging**
